### ISSUE TITLE
Worth using folders to organise include dir?

### ISSUE THREAD

**Issue by grantus** [grantus/grave#18]
We may end up with a large number of headers in a single folder which could impact readability.

**Comment by xenomorpheus** [comment]
Sounds reasonable. Perhaps folder name by functionality group or library name ?

**Comment by grantus** [comment]
yeah was thinking of essentially mirroring the src folder

**Comment by xenomorpheus** [comment]
Sounds reasonable

**Comment by grantus** [comment]
Given I am forging ahead with the c++1y conversion, this is done in that feature branch at the moment...
