### ISSUE TITLE
core: c++1y conversion

### ISSUE THREAD

**Issue by grantus** [grantus/grave#43]
Investigate and if not a monumental undertaking, consider conversion of core to C++ 14 (1y on old compilers).

This provides us with many benefits:
  * GLM
  * FBX SDK
  * glbinding (C++ namespaced OpenGL bindings)
  * GoogleTest
  * Awesomium (UI library)

**Comment by grantus** [comment]
So this is going to take a few (3 full-time) days to complete I'd say.

**Comment by xenomorpheus** [comment]
So done by Sunday arvo :)

**Comment by grantus** [comment]
Probably more like 4-5 days full time haha.
